let stockProductos = [
    {id: 1, nombre: "pulsera1", tipo: "pulsera", cantidad: 1, desc: "Un pulsera que re va con vos", precio: 1200, talle: "L", img: './img/pul-1.png'},
    {id: 2, nombre: "pulsera2", tipo: "pulsera", cantidad: 1, desc: "Un pulsera que re va con vos", precio: 1100, talle: "L", img: './img/pul-2.png'},
    {id: 3, nombre: "pulsera3", tipo: "pulsera", cantidad: 1, desc: "Un pulsera que re va con vos", precio: 1200, talle: "M", img: './img/pul-3.png'},
    {id: 4, nombre: "pulsera4", tipo: "pulsera", cantidad: 1, desc: "Un pulsera que re va con vos", precio: 1400, talle: "M", img: './img/pul-4.png'},
    {id: 5, nombre: "pulsera5", tipo: "pulsera", cantidad: 1, desc: "Un pulsera que re va con vos", precio: 1200, talle: "S", img: './img/pul-5.png'},
    {id: 6, nombre: "pulsera", tipo: "pulsera", cantidad: 1, desc: "Un pulsera que re va con vos", precio: 1500, talle: "S", img: './img/pul-6.png'},
    {id: 7, nombre: "modelo1", tipo: "modelo", cantidad: 1, desc: "Un modelo que re va con vos", precio: 500, talle: "L", img: './img/pul-7.png'},
    {id: 8, nombre: "modelo2", tipo: "modelo", cantidad: 1, desc: "Un modelo  que re va con vos", precio: 500, talle: "L", img: './img/pul-9.png'},
    {id: 9, nombre: "modelo3", tipo: "modelo", cantidad: 1, desc: "Un modelo que re va con vos", precio: 500, talle: "M", img: './img/pul-10.png'},
    {id: 10, nombre: "modelo4", tipo: "modelo", cantidad: 1, desc: "Un modelo que re va con vos", precio: 700, talle: "M", img: './img/pul-11.png'},
    {id: 11, nombre: "aritos1", tipo: "aritos", cantidad: 1,desc: "Unos aritos que re va con vos", precio: 700, talle: "S", img: './img/corazones.png'},
    {id: 12, nombre: "aritos2", tipo: "aritos", cantidad: 1, desc: "Unos aritos que re va con vos", precio: 700, talle: "S", img: './img/aritos-2.png'},
    {id: 13, nombre: "aritos3", tipo: "aritos", cantidad: 1, desc: "Unos aritos que re va con vos", precio: 900, talle: "L", img: './img/pul-12.png'},
    {id: 14, nombre: "aritos4", tipo: "aritos", cantidad: 1, desc: "Unos aritos que re va con vos", precio: 1400, talle: "S", img: './img/pul-13.png'},
    {id: 15, nombre: "aritos5", tipo: "aritos", cantidad: 1, desc: "Unos aritos que re va con vos", precio: 7000, talle: "L", img: './img/pul-14.png'},
    {id: 16, nombre: "aritos7", tipo: "aritos", cantidad: 1, desc: "Unos aritos que re va con vos", precio: 777, talle: "S", img: './img/pul-14.png'},
    {id: 17, nombre: "aritos8", tipo: "aritos", cantidad: 1, desc: "Unos aritos que re va con vos", precio: 234, talle: "S", img: './img/pul-15.png'},
    {id: 18, nombre: "juegos1", tipo: "juegos", cantidad: 1, desc: "Una joya que re va con vos", precio: 155600, talle: "M", img: './img/banner02.png'},
    {id: 19, nombre: "juegos2", tipo: "juegos", cantidad: 1, desc: "Una joya que re va con vos", precio: 1600, talle: "L", img: './img/banner04.png'},
    {id: 20, nombre: "juegos3", tipo: "juegos", cantidad: 1, desc: "Una joya que re va con vos", precio: 3200, talle: "L", img: './img/banner02.png'},
    {id: 21, nombre: "juegos5", tipo: "juegos", cantidad: 1, desc: "Una joya que re va con vos", precio: 2300, talle: "M", img: './img/banner01.png'},
    {id: 22, nombre: "juegos6", tipo: "juegos", cantidad: 1, desc: "Una joya que re va con vos", precio: 5600, talle: "M", img: './img/banner04.png'},
    {id: 23, nombre: "juegos7", tipo: "juegos", cantidad: 1, desc: "Una joya que re va con vos", precio: 1700, talle: "S", img: './img/banner02.png'},
    {id: 24, nombre: "juegos8", tipo: "juegos", cantidad: 1, desc: "Una joya que re va con vos", precio: 800, talle: "S", img: './img/banner01.png'},
]